[project]
name = "pricebot"
version = "0.1.0"
description = "Craigslist web scraper for cars and apartments"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "selenium>=4.35.0",
]
